## AN EMULATION OF HOW OUR SVC.YAML IS LAID OUT..
services:
  nakama:
    build: .
    container_name: ttt_srv
    environment:
      - NAKAMA_DATABASE_ADDRESS=${NAKAMA_DATABASE_ADDRESS}
      - SERVER_KEY=${SERVER_KEY}
      - CONSOLE_PASSWORD=${CONSOLE_PASSWORD}
    expose:
      - "7350" # api server
      - "7351" # console
      - "7349" # gRPC api server
      - "7348" # gRPC for console
  proxy:
    build:
      dockerfile: local/Dockerfile.caddy
    container_name: ttt_pxy
    ports:
      - "8080:8080"
    # cloud run doenst have this
    depends_on:
      - nakama