## SEE https://docs.cloud.google.com/run/docs/reference/yaml/v1
## THIS is how my main deployment looks.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ttt-nk-prod
  annotations:
    run.googleapis.com/ingress: all

  labels:
    cloud.googleapis.com/location: ${region}
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: "gen2"
    spec:
      # This service account requires access to the secret manager secrets
      serviceAccountName: "${svc_account}"
      # These can start up independently
      containers:
      - name: proxy
        image: ${region}-docker.pkg.dev/${p_id}/${repo}/caddy-proxy:latest
        ports:
        - containerPort: 8080

      # --- Main Nakama Container ---
      - name: nakama
        image: ${region}-docker.pkg.dev/${p_id}/${repo}/nakama:latest
        env:
        - name: NAKAMA_DATABASE_ADDRESS
          valueFrom:
            secretKeyRef:
              name: NAKAMA_DB_ADDRESS
              key: latest
        - name: SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: NAKAMA_SERVER_KEY
              key: latest
        - name: CONSOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: NAKAMA_CONSOLE_PASSWORD
              key: latest